version: '3.6'

services:

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "7001:15672"
      - "7002:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    restart: always
  api:
    build: .
    container_name: app
    image: app
    environment:
      REDIS_PASSWORD: test
    ports:
      - 8080:8080
    depends_on:
      - redis
      - rabbitmq


